# Downloads the new exercises when given a link and an exercise number

name: 'Download Exercises'

on:
  workflow_dispatch:
    inputs:
      material_link:
        description: 'Link zum Material'
        required: true
      blatt_nr:
        description: 'Nummer des Übungsblatts'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download the provided link and extract into a subfolder
        run: |
          mkdir blatt-${{ github.event.inputs.blatt_nr }}
          wget ${{ github.event.inputs.material_link }} -O - | tar -xz -C blatt-${{ github.event.inputs.blatt_nr }}
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add blatt-${{ github.event.inputs.blatt_nr }}
          git commit -m "Download new exercises"
          git push
